{% set name = "tiledb" %}
{% set version = "0.34.0" %}
{% set sha256 = "ce4995f7455bebfa651fa45a795b07e8bc79867a6feb9b8523c8066ac817e44c" %}

package:
  name: tiledb-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make
  host:
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - scikit-build-core
    - python
    - numpy
    - pybind11
    - tiledb >=2.28.0,<2.29
  run:
    - python
    - packaging

{% if python_impl != 'pypy' %}
test:
  requires:
    - hypothesis
    - pyarrow
    - pytest
    - pandas
    - psutil
  imports:
    - tiledb
  source_files:
    - tiledb/tests/
  commands:
    - python -c "import tiledb; tiledb.libtiledb.version()"
    - python -c "import tiledb; assert tiledb.VFS().supports('s3')"
    - pytest -v --ignore-glob='*_examples.py' --ignore-glob='*_dask.py'
{% endif %}

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to the TileDB sparse and dense multi-dimensional array storage manager
  description: |
    TileDB-Py is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html
  dev_url: https://github.com/TileDB-Inc/TileDB-Py

extra:
  recipe-maintainers:
    - ihnorton
    - jdblischak
    - shelnutt2
    - kounelisagis
