{% set name = "tiledb" %}
{% set version = "0.2.0" %}
{% set sha256 = "59c2cd301bcbf8bf397ca8b1bde4a102d11e309ff25199c5a2dfb196cc96cd54" %}

package:
  name: tiledb-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]
  script: python setup.py install --tiledb="$PREFIX" --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools >18.0
    - setuptools_scm >1.5.4
    - cython
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - tiledb 1.2.*

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - tiledb 1.2.*

test:
  imports:
    - tiledb
  commands:
    - python -c "import tiledb; tiledb.libtiledb.version()"

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface to the TileDB sparse and dense multi-dimensional array storage manager'
  description: |
    TileDB-Py is the python interface to the TielDB array storage manager.  
    TileDB  is an efficient multi-dimensional array management system which introduces 
    a novel on-disk format that can store dense and sparse array data with 
    support for fast reads and updates and reads. It features excellent compression, and an efficient 
    parallel I/O system with high scalability.
  doc_url: https://api-reference.tiledb.io/python-api.html
  dev_url: https://github.com/TileDB-Inc/TileDB-Py

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
