{% set name = "tiledb" %}
{% set version = "0.24.0" %}
{% set sha256 = "6e1f2f0391d5f5d76ae832da6add17d38d9c506b7105fe19823628b5ddb39af6" %}

package:
  name: tiledb-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win32]
  skip: true  # [win and py2k]
requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3.0                            # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11 <2.11                         # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - python
    - cython <3.0
    - numpy
    - pybind11 <2.11
    - tiledb >=2.18.0,<2.19
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - packaging

{% if python_impl != 'pypy' %}
test:
  requires:
    - hypothesis
    - pyarrow
    - pytest
    - pandas
    - psutil
  imports:
    - tiledb
  source_files:
    - tiledb/tests/
  commands:
    - python -c "import tiledb; tiledb.libtiledb.version()"
    - python -c "import tiledb; assert tiledb.VFS().supports('s3')"
    - pytest -v --ignore-glob='*_examples.py' --ignore-glob='*_dask.py'
{% endif %}

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to the TileDB sparse and dense multi-dimensional array storage manager
  description: |
    TileDB-Py is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://api-reference.tiledb.io/python-api.html
  dev_url: https://github.com/TileDB-Inc/TileDB-Py

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - shelnutt2
    - ihnorton
    - nguyenv
