{% set name = "tiledb" %}
{% set version = "0.4.3" %}
{% set sha256 = "79d8cac0cfd3e1d239b869ca5508df7348f35caf646955447b9997726485a300" %}

package:
  name: tiledb-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win32]
  skip: True  # [win and py2k]
  features:  # [win]
    - vc14  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - wheel
    - setuptools
    - setuptools_scm
    - cython
    - numpy
    - tiledb 1.6.*

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - tiledb 1.6.*

test:
  imports:
    - tiledb
  commands:
    - python -c "import tiledb; tiledb.libtiledb.version()"
    - python -c "import tiledb; assert tiledb.VFS().supports('s3')"

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface to the TileDB sparse and dense multi-dimensional array storage manager'
  description: |
    TileDB-Py is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://api-reference.tiledb.io/python-api.html
  dev_url: https://github.com/TileDB-Inc/TileDB-Py

extra:
  recipe-maintainers:
    - stavrospapadopoulos
    - jakebolewski
    - tdenniston
    - ihnorton
