appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OdG63/dfsM83FHrcGVyQG9UY7wx0SAZALR+It0CpbxhyWT/zw/8NPet0wqpuozXXnhxOFrTADB4kXuy7046SvDdH5P6Fl2QK62lPlxgXnzg5d/FO6gyXlaIzn43bAeMH9HSHHegguuiVt9+fcFlsCwiCMFD7giiUtWoBTxogYjL5nqlCxN5/xOAGepAiqj7k3E/z3azomwh45Pc0ZZs6csB/iWFaA6QPiX3y5WvZNScgX3QEKWIn53DltyacRdcKs7xYzgDgWZr/+vehiUumo7frQA4qVBcHiXDTSE+jILGSvwQG2Z7ZP79KgQkBEJYYEGMJZt9AP2bf5DMXqJYSIcB2UyhWEN6Xl9BRETpvKgqQwgHHY57DDd+Im4Gjn9eiDrDePjCIl0wl0ij3ZPP6N3dCwkfTUFtixZjE3i+kqQBXBQIJCRCEDiUiuZVc9dX4jmLM+PQV85x9qmaec3LBREQ4YnYOTW1xSW3s7LMxdssqZ5SMPbt8XJDGEbxqzktOUi5fPCG1rNraY66zFLjA5Ctipu5Ng05DWGVlWhF3d4i4f8ldBX9h0htA/6Z1soUIKG7B7wlybV8Tt+F3GkvjDIdSbPT4ORYCHinyZUs0xoo9kd4nfwFasOADcycFEx81TGInuJtYsTGANfQbm/vn55ZHiDEftC/1OVuTk6p89bQ=}
conda_forge_output_validation: true
